export enum Role {
    // AE='DF,DR',
    // Noncall='DF',
    // Nonred='DR',
    // Quote='QI||QRU||QRM',
    // Quotea='QI,QRU,QRM',
    one='QI,DR',
    two='QI,QRU,QRP,DF,DR,ARRP',
    three='QI,QRU,QRP,DF,DR',
    four='QI,QRU,QRM,QRP,DF,DR',
    five='QI,QRU,QRM,QRP,DF,DR,ARRP',
    six='QI,QRU,QRP,DR',
    seven='DF',
    eight='DF,ARRP',
    nine='DF,DR',
    ten='DR',
    hi='QI',
    ho='QI,QRU',
    jo='QI,QRU,QRM',
    lo='QI,QRU,QRP',
    ok='QI,QRU,QRM,QRP',
    ao='DR,ARRP',
    so='DR,DF,ARRP'
}
